#!/usr/bin/env python3
"""
城市参考数据
包含中国主要城市的基础数据，用于爬虫失败时的备用数据源
数据来源: 国家统计局、各城市政府官网
"""

# 城市基础数据（人口单位：万人，GDP单位：亿元，面积单位：km²）
CITY_REFERENCE_DATA = {
    '成都': {
        'name_en': 'Chengdu',
        'province': '四川',
        'population': 2119,
        'gdp': 22074,
        'area': 14335,
        'latitude': 30.5728,
        'longitude': 104.0668,
        'climate': '亚热带季风气候',
        'avg_temp': 16.5,
        'slogan': '成都，一座来了就不想走的城市',
        'description': '成都，四川省省会，西南地区重要的中心城市。这里有着悠久的历史文化，是三国文化的重要发源地。成都以其悠闲的生活节奏、丰富的美食文化和独特的茶馆文化而闻名。',
        'famous_places': ['武侯祠', '杜甫草堂', '宽窄巷子', '锦里', '大熊猫繁育研究基地'],
    },
    '杭州': {
        'name_en': 'Hangzhou',
        'province': '浙江',
        'population': 1237,
        'gdp': 20059,
        'area': 16850,
        'latitude': 30.2741,
        'longitude': 120.1551,
        'climate': '亚热带季风气候',
        'avg_temp': 17.8,
        'slogan': '人间天堂，品质杭州',
        'description': '杭州，浙江省省会，长三角城市群中心城市。以西湖闻名天下，是中国著名的旅游城市。杭州也是中国互联网经济的重要中心，阿里巴巴等众多科技企业总部所在地。',
        'famous_places': ['西湖', '灵隐寺', '雷峰塔', '西溪湿地', '千岛湖'],
    },
    '青岛': {
        'name_en': 'Qingdao',
        'province': '山东',
        'population': 1034,
        'gdp': 15760,
        'area': 11293,
        'latitude': 36.0671,
        'longitude': 120.3826,
        'climate': '温带季风气候',
        'avg_temp': 13.1,
        'slogan': '红瓦绿树、碧海蓝天',
        'description': '青岛，山东省副省级城市，中国著名的海滨城市。这里有着独特的欧陆风情建筑和美丽的海滨风光。青岛啤酒、海鲜美食享誉全国。',
        'famous_places': ['栈桥', '八大关', '崂山', '金沙滩', '青岛啤酒博物馆'],
    },
    '厦门': {
        'name_en': 'Xiamen',
        'province': '福建',
        'population': 528,
        'gdp': 8067,
        'area': 1701,
        'latitude': 24.4795,
        'longitude': 118.0894,
        'climate': '亚热带海洋性季风气候',
        'avg_temp': 21.0,
        'slogan': '海上花园，温馨厦门',
        'description': '厦门，福建省副省级城市，中国最美的海滨城市之一。这里有着独特的闽南文化、优美的海岛风光和温和的气候，是著名的旅游度假胜地。',
        'famous_places': ['鼓浪屿', '南普陀寺', '环岛路', '曾厝垵', '厦门大学'],
    },
    '大连': {
        'name_en': 'Dalian',
        'province': '辽宁',
        'population': 745,
        'gdp': 8752,
        'area': 12574,
        'latitude': 38.9140,
        'longitude': 121.6147,
        'climate': '温带季风气候',
        'avg_temp': 10.9,
        'slogan': '浪漫之都，时尚大连',
        'description': '大连，辽宁省副省级城市，北方著名的海滨城市。这里有着美丽的海滨风光、现代化的城市建设和独特的俄日风情建筑。',
        'famous_places': ['星海广场', '老虎滩', '金石滩', '棒棰岛', '滨海路'],
    },
    '昆明': {
        'name_en': 'Kunming',
        'province': '云南',
        'population': 850,
        'gdp': 7864,
        'area': 21012,
        'latitude': 25.0389,
        'longitude': 102.7183,
        'climate': '高原季风气候',
        'avg_temp': 15.5,
        'slogan': '春城昆明，四季如春',
        'description': '昆明，云南省省会，素有"春城"美誉。这里四季如春、气候宜人，是中国著名的旅游城市和花卉之都。',
        'famous_places': ['滇池', '石林', '翠湖', '金马碧鸡坊', '西山'],
    },
    '苏州': {
        'name_en': 'Suzhou',
        'province': '江苏',
        'population': 1290,
        'gdp': 24653,
        'area': 8657,
        'latitude': 31.2990,
        'longitude': 120.5853,
        'climate': '亚热带季风气候',
        'avg_temp': 17.0,
        'slogan': '人间天堂，东方威尼斯',
        'description': '苏州，江苏省地级市，中国历史文化名城。以古典园林闻名于世，素有"上有天堂，下有苏杭"之美誉。苏州工业园区是中国现代化程度最高的开发区之一。',
        'famous_places': ['拙政园', '虎丘', '周庄', '寒山寺', '留园'],
    },
    '珠海': {
        'name_en': 'Zhuhai',
        'province': '广东',
        'population': 247,
        'gdp': 4045,
        'area': 1736,
        'latitude': 22.2710,
        'longitude': 113.5767,
        'climate': '亚热带海洋性季风气候',
        'avg_temp': 22.5,
        'slogan': '浪漫之城，百岛之市',
        'description': '珠海，广东省地级市，珠三角中海洋面积最大的城市。这里有着优美的海滨风光、宜人的气候和高品质的城市环境，连续多年被评为中国最宜居城市。',
        'famous_places': ['渔女像', '情侣路', '横琴岛', '圆明新园', '外伶仃岛'],
    },
    '威海': {
        'name_en': 'Weihai',
        'province': '山东',
        'population': 291,
        'gdp': 3728,
        'area': 5799,
        'latitude': 37.5091,
        'longitude': 122.1209,
        'climate': '温带季风气候',
        'avg_temp': 12.7,
        'slogan': '走遍四海，还是威海',
        'description': '威海，山东省地级市，中国第一个国家卫生城市。这里有着优美的海滨风光、清新的空气和较低的生活成本，是著名的宜居城市和养老胜地。',
        'famous_places': ['刘公岛', '成山头', '威海国际海水浴场', '定远舰', '环翠楼'],
    },
    '南京': {
        'name_en': 'Nanjing',
        'province': '江苏',
        'population': 942,
        'gdp': 17421,
        'area': 6587,
        'latitude': 32.0603,
        'longitude': 118.7969,
        'climate': '亚热带季风气候',
        'avg_temp': 16.5,
        'slogan': '六朝古都，博爱之都',
        'description': '南京，江苏省省会，中国四大古都之一。这里有着深厚的历史文化底蕴，是中华文明的重要发祥地之一。南京也是长三角地区重要的科教文化中心。',
        'famous_places': ['中山陵', '夫子庙', '明孝陵', '玄武湖', '总统府'],
    },
    # 其他热门城市
    '北京': {
        'name_en': 'Beijing',
        'province': '北京',
        'population': 2188,
        'gdp': 43760,
        'area': 16410,
        'latitude': 39.9042,
        'longitude': 116.4074,
        'climate': '温带季风气候',
        'avg_temp': 13.3,
        'slogan': '首善之区，千年古都',
        'description': '北京，中国首都，全国政治、文化、国际交往中心。这里汇聚了中国最顶尖的高校、医院和文化机构，同时也保存着丰富的历史文化遗产。',
        'famous_places': ['故宫', '长城', '天安门', '颐和园', '天坛'],
    },
    '上海': {
        'name_en': 'Shanghai',
        'province': '上海',
        'population': 2489,
        'gdp': 47218,
        'area': 6340,
        'latitude': 31.2304,
        'longitude': 121.4737,
        'climate': '亚热带季风气候',
        'avg_temp': 17.6,
        'slogan': '魔都上海，东方明珠',
        'description': '上海，中国经济、金融、贸易、航运中心。这里是中国现代化程度最高的城市，汇聚了全球顶级企业和人才，同时也保留着独特的海派文化。',
        'famous_places': ['外滩', '东方明珠', '南京路', '豫园', '迪士尼乐园'],
    },
    '深圳': {
        'name_en': 'Shenzhen',
        'province': '广东',
        'population': 1768,
        'gdp': 34606,
        'area': 1997,
        'latitude': 22.5431,
        'longitude': 114.0579,
        'climate': '亚热带海洋性季风气候',
        'avg_temp': 23.0,
        'slogan': '来了就是深圳人',
        'description': '深圳，中国经济特区，科技创新之都。这里是中国改革开放的前沿阵地，汇聚了华为、腾讯等众多科技巨头，是中国最具活力和创新精神的城市。',
        'famous_places': ['世界之窗', '欢乐谷', '大梅沙', '东部华侨城', '深圳湾'],
    },
    '广州': {
        'name_en': 'Guangzhou',
        'province': '广东',
        'population': 1881,
        'gdp': 30355,
        'area': 7434,
        'latitude': 23.1291,
        'longitude': 113.2644,
        'climate': '亚热带季风气候',
        'avg_temp': 22.8,
        'slogan': '食在广州，千年商都',
        'description': '广州，广东省省会，中国南方最大的城市。这里是中国对外贸易的重要门户，以美食、骑楼建筑和岭南文化闻名于世。',
        'famous_places': ['广州塔', '白云山', '陈家祠', '沙面', '长隆'],
    },
    '三亚': {
        'name_en': 'Sanya',
        'province': '海南',
        'population': 103,
        'gdp': 925,
        'area': 1919,
        'latitude': 18.2528,
        'longitude': 109.5119,
        'climate': '热带海洋性季风气候',
        'avg_temp': 25.8,
        'slogan': '热带天堂，度假胜地',
        'description': '三亚，海南省地级市，中国最南端的热带滨海旅游城市。这里有着得天独厚的热带海滨风光、温暖的气候和优质的沙滩，是中国最热门的度假胜地。',
        'famous_places': ['亚龙湾', '天涯海角', '南山寺', '蜈支洲岛', '大东海'],
    },
    '海口': {
        'name_en': 'Haikou',
        'province': '海南',
        'population': 290,
        'gdp': 2102,
        'area': 3145,
        'latitude': 20.0440,
        'longitude': 110.1999,
        'climate': '热带海洋性季风气候',
        'avg_temp': 24.5,
        'slogan': '椰城海口，阳光海岸',
        'description': '海口，海南省省会，中国最大的经济特区首府。这里有着独特的椰风海韵、温暖的气候和较低的生活成本，是冬季避寒的理想目的地。',
        'famous_places': ['骑楼老街', '假日海滩', '万绿园', '火山口公园', '西秀海滩'],
    },
    '丽江': {
        'name_en': 'Lijiang',
        'province': '云南',
        'population': 127,
        'gdp': 620,
        'area': 20600,
        'latitude': 26.8721,
        'longitude': 100.2299,
        'climate': '高原季风气候',
        'avg_temp': 13.0,
        'slogan': '世界文化遗产，高原姑苏',
        'description': '丽江，云南省地级市，世界文化遗产地。这里有着保存完好的古城、壮丽的雪山和独特的纳西族文化，是中国最热门的旅游目的地之一。',
        'famous_places': ['丽江古城', '玉龙雪山', '束河古镇', '泸沽湖', '虎跳峡'],
    },
    '大理': {
        'name_en': 'Dali',
        'province': '云南',
        'population': 333,
        'gdp': 1608,
        'area': 29459,
        'latitude': 25.6065,
        'longitude': 100.2679,
        'climate': '高原季风气候',
        'avg_temp': 15.5,
        'slogan': '风花雪月，诗意大理',
        'description': '大理，云南省地级市，以苍山洱海闻名。这里有着独特的白族文化、温和的气候和悠闲的生活节奏，是"数字游民"和旅居者的热门选择。',
        'famous_places': ['大理古城', '洱海', '苍山', '双廊', '崇圣寺三塔'],
    },
    '西双版纳': {
        'name_en': 'Xishuangbanna',
        'province': '云南',
        'population': 130,
        'gdp': 680,
        'area': 19124,
        'latitude': 22.0017,
        'longitude': 100.7991,
        'climate': '热带季风气候',
        'avg_temp': 22.0,
        'slogan': '热带雨林，傣乡风情',
        'description': '西双版纳，云南省自治州，中国唯一的热带雨林自然保护区所在地。这里有着独特的傣族文化、丰富的热带动植物资源和温暖的气候。',
        'famous_places': ['曼听公园', '野象谷', '热带植物园', '告庄西双景', '橄榄坝'],
    },
    '桂林': {
        'name_en': 'Guilin',
        'province': '广西',
        'population': 494,
        'gdp': 2435,
        'area': 27809,
        'latitude': 25.2742,
        'longitude': 110.2900,
        'climate': '亚热带季风气候',
        'avg_temp': 19.3,
        'slogan': '桂林山水甲天下',
        'description': '桂林，广西壮族自治区地级市，世界著名的山水旅游城市。"桂林山水甲天下"的美誉流传已久，这里有着独特的喀斯特地貌和秀丽的山水风光。',
        'famous_places': ['漓江', '阳朔', '象鼻山', '龙脊梯田', '两江四湖'],
    },
    '重庆': {
        'name_en': 'Chongqing',
        'province': '重庆',
        'population': 3212,
        'gdp': 29129,
        'area': 82400,
        'latitude': 29.5630,
        'longitude': 106.5516,
        'climate': '亚热带季风气候',
        'avg_temp': 18.4,
        'slogan': '山城重庆，魔幻8D城市',
        'description': '重庆，中国四大直辖市之一，西南地区最大的城市。这里有着独特的山城地形、火辣的美食文化和魔幻的城市景观，被称为"8D魔幻城市"。',
        'famous_places': ['洪崖洞', '解放碑', '长江索道', '磁器口', '武隆天坑'],
    },
    '西安': {
        'name_en': 'Xi\'an',
        'province': '陕西',
        'population': 1316,
        'gdp': 11412,
        'area': 10752,
        'latitude': 34.3416,
        'longitude': 108.9398,
        'climate': '温带季风气候',
        'avg_temp': 14.2,
        'slogan': '千年古都，丝路起点',
        'description': '西安，陕西省省会，中国四大古都之一。这里曾是十三朝古都，拥有秦始皇兵马俑等世界级文化遗产，是中华文明的重要发祥地。',
        'famous_places': ['兵马俑', '大雁塔', '古城墙', '华清池', '回民街'],
    },
}

# 城市租金参考数据（元/月，一居室）
RENT_REFERENCE = {
    '北京': 5500,
    '上海': 5000,
    '深圳': 4500,
    '广州': 3500,
    '杭州': 3200,
    '成都': 2000,
    '南京': 2800,
    '苏州': 2500,
    '厦门': 2800,
    '青岛': 2000,
    '大连': 1800,
    '昆明': 1500,
    '珠海': 2200,
    '威海': 1200,
    '三亚': 2500,
    '海口': 1800,
    '丽江': 1200,
    '大理': 1300,
    '西双版纳': 1000,
    '桂林': 1300,
    '重庆': 1800,
    '西安': 1800,
}


def get_city_data(city_name: str) -> dict:
    """获取城市参考数据"""
    data = CITY_REFERENCE_DATA.get(city_name, {}).copy()
    if city_name in RENT_REFERENCE:
        data['avg_rent'] = RENT_REFERENCE[city_name]
    return data


def get_all_cities() -> list:
    """获取所有城市名称"""
    return list(CITY_REFERENCE_DATA.keys())
